### ISSUE TITLE
Incompatibility with Minecraft 1.21 - No enum constant error

### ISSUE THREAD

**Issue by yummongi** [unldenis/Corpse#13]
I’m experiencing an issue with the Corpse plugin when running it on a Minecraft 1.21 server. The plugin throws an exception when attempting to spawn a corpse. The error seems to be related to an undefined enum constant in the VersionEnum class.

Steps to Reproduce:

	1.	Run a Minecraft server with version 1.21.
	2.	Install the Corpse plugin (version 1.0.10).
	3.	Execute the command /spawncorpse <player_name>.
	4.	Observe the error in the console.

Expected Behavior:
The plugin should correctly spawn a corpse without errors.

Actual Behavior:
The plugin fails to execute the command, and the following error is thrown:
[00:14:39 ERROR]: Command exception: /spawncorpse Limes_
org.bukkit.command.CommandException: Unhandled exception executing command 'spawncorpse' in plugin Corpse v1.0.10
Caused by: java.lang.IllegalArgumentException: No enum constant com.github.unldenis.corpse.util.VersionUtil.VersionEnum.CRAFTBUK
	at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at Corpse-1.0.10.jar/com.github.unldenis.corpse.util.VersionUtil$VersionEnum.valueOf(VersionUtil.java:55) ~[Corpse-1.0.10.jar:?]
	at Corpse-1.0.10.jar/com.github.unldenis.corpse.util.VersionUtil.isBelow(VersionUtil.java:47) ~[Corpse-1.0.10.jar:?]
	at Corpse-1.0.10.jar/com.github.unldenis.corpse.logic.PacketLoader.load(PacketLoader.java:65) ~[Corpse-1.0.10.jar:?]
	at Corpse-1.0.10.jar/com.github.unldenis.corpse.logic.Corpse.<init>(Corpse.java:76) ~[Corpse-1.0.10.jar:?]
	at Corpse-1.0.10.jar/com.github.unldenis.corpse.api.CorpseAPI.spawnCorpse(CorpseAPI.java:74) ~[Corpse-1.0.10.jar:?]
	at Corpse-1.0.10.jar/com.github.unldenis.corpse.command.SpawnCorpseCommand.onCommand(SpawnCorpseCommand.java:44) ~[Corpse-1.0.10.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 27 more
	
	Environment:

	•	Minecraft version: 1.21
	•	Corpse plugin version: 1.0.10

**Comment by unldenis** [comment]
Closing since 2.0.0 supports newest versions!
