### ISSUE TITLE
Cannot measure distance between World and AnotherWorld

### ISSUE THREAD

**Issue by CryLegende** [unldenis/Corpse#3]
Hello ^^
The plugin spam the console with the same error if the player is not in the same world as the spawned corpse
``[16:31:35 WARN]: [Corpse] Plugin Corpse v1.0.7-SNAPSHOT generated an exception while executing task 76
java.lang.IllegalArgumentException: Cannot measure distance between spawn and arena
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.github.unldenis.corpse.manager.CorpsePool.lambda$corpseTick$0(CorpsePool.java:86) ~[Corpse (1).jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]``
        
        Thank you for your help :)

**Comment by unldenis** [comment]
Fixed since 1.0.8 .
