### ISSUE TITLE
Could not pass event PlayerDeathEvent to Corpse v1.0.9-SNAPSHOT

### ISSUE THREAD

**Issue by stephan-steinmiller** [unldenis/Corpse#5]
I am using 1.0.9 and ProtocolLib v5.0.0-rc1 because their 4.8.0 release did not work for me.
this is the full log I got:
```
... issued server command: /kill @s
[23:41:01 ERROR]: Could not pass event PlayerDeathEvent to Corpse v1.0.9-SNAPSHOT
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib (1).jar:?]
        at com.github.unldenis.corpse.logic.packet.WrapperPlayerInfo.load(WrapperPlayerInfo.java:46) ~[Corpse.jar:?]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
        at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425) ~[?:?]
        at com.github.unldenis.corpse.logic.PacketLoader.load(PacketLoader.java:68) ~[Corpse.jar:?]
        at com.github.unldenis.corpse.logic.Corpse.<init>(Corpse.java:76) ~[Corpse.jar:?]
        at com.github.unldenis.corpse.logic.Corpse.<init>(Corpse.java:92) ~[Corpse.jar:?]
        at com.github.unldenis.corpse.manager.CorpsePool.handleDeath(CorpsePool.java:195) ~[Corpse.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-516]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-516]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-516]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:923) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:915) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1480) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:965) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1084) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.kill(LivingEntity.java:318) ~[?:?]
        at net.minecraft.server.commands.KillCommand.kill(KillCommand.java:25) ~[?:?]
        at net.minecraft.server.commands.KillCommand.register(KillCommand.java:18) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2290) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2250) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-516]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by stephan-steinmiller** [comment]
Is this because I am on the latest Minecraft version 1.19.4 and this plugin doesn't support that version yet?

**Comment by Technofied** [comment]
Same issue here.

**Comment by stephan-steinmiller** [comment]
This seemed to be because of the wrong protocol lib version, it worked with the 5.0rc but now 5.0 got released so it should work again.
